# Funding options for proc
# Uncomment and configure the platforms you want to use

github: [yazeed]
# patreon: yazeed
# open_collective: proc-cli
# ko_fi: yazeedaloyoun
# custom: ["https://yazeed.com"]
