title: proc
description: Semantic CLI tool for process management. Target by port, PID, name or path.
url: https://yazeed.github.io
baseurl: /proc
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

permalink: /blog/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
