title: proc
description: Semantic CLI tool for process management. Target by port, PID, name or path.
url: https://yazeed.github.io
baseurl: /proc

permalink: /posts/:title/

plugins:
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
